language: cpp
matrix:
  include:
    - os: linux
      env: IMAGE=ubuntu:rolling COMMAND=build_linux_gcc_coverall_ubuntu RELEASE_FILES="$TRAVIS_BUILD_DIR/build/*.xz"
      services: docker
    - os: linux
      env: IMAGE=i386/ubuntu:rolling COMMAND=build_linux_gcc_ubuntu_i386
      services: docker
    - os: linux
      env: IMAGE=ubuntu:xenial COMMAND=build_linux_gcc_ubuntu
      services: docker
    - os: linux
      env: IMAGE=debian:stable COMMAND=build_linux_gcc_debian
      services: docker
    - os: linux
      env: IMAGE=fedora:latest COMMAND=build_linux_gcc_fedora
      services: docker
    - os: linux
      env: IMAGE=ubuntu:rolling COMMAND=build_linux_clang_ubuntu
      services: docker
    - os: linux
      env: IMAGE=x86_64 COMMAND=make_py_wheel_py RELEASE_FILES="$TRAVIS_BUILD_DIR/python/dist/*manylinux*.whl"
      script:
        - $TRAVIS_BUILD_DIR/python/make_py_wheel.sh ${IMAGE}
        - if [[ "$RELEASE_FILES" != "" ]]; then ls -l $RELEASE_FILES          ; fi
      services: docker
    - os: linux
      env: IMAGE=i686 COMMAND=make_py_wheel_py RELEASE_FILES="$TRAVIS_BUILD_DIR/python/dist/*manylinux*.whl"
      script:
        - $TRAVIS_BUILD_DIR/python/make_py_wheel.sh ${IMAGE}
        - if [[ "$RELEASE_FILES" != "" ]]; then ls -l $RELEASE_FILES          ; fi
      services: docker
    - os: linux
      env: IMAGE=x86_64 COMMAND=make_py_wheel_tf RELEASE_FILES="$TRAVIS_BUILD_DIR/tensorflow/dist/*.whl"
      script:
        - $TRAVIS_BUILD_DIR/tensorflow/make_py_wheel.sh
        - if [[ "$RELEASE_FILES" != "" ]]; then ls -l $RELEASE_FILES          ; fi
      services: docker
    - os: osx
      osx_image: xcode9.3
      env: IMAGE=native COMMAND=build_osx
    - os: osx
      osx_image: xcode9.4
      env: IMAGE=native COMMAND=build_osx
    - os: osx
      osx_image: xcode9.2
      env: IMAGE=native COMMAND=build_osx
    - os: osx
      osx_image: xcode9.4
      env: IMAGE=native COMMAND=make_py_wheel_mac_py RELEASE_FILES="$TRAVIS_BUILD_DIR/python/dist/delocated_wheel/*.whl"
      script:
        - $TRAVIS_BUILD_DIR/python/make_py_wheel_mac.sh
        - if [[ "$RELEASE_FILES" != "" ]]; then ls -l $RELEASE_FILES          ; fi
    - os: osx
      osx_image: xcode9.4
      env: IMAGE=native COMMAND=make_py_wheel_mac_tf RELEASE_FILES="$TRAVIS_BUILD_DIR/tensorflow/dist/*.whl"
      script:
        - $TRAVIS_BUILD_DIR/tensorflow/make_py_wheel_mac.sh
        - if [[ "$RELEASE_FILES" != "" ]]; then ls -l $RELEASE_FILES          ; fi
script:
  - $TRAVIS_BUILD_DIR/test.sh ${IMAGE} ${COMMAND}
  - if [[ "$RELEASE_FILES" != "" ]]; then ls -l $RELEASE_FILES          ; fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: WQph3aOhH3YsXaZw9VbtNa79tEeh1W/7r76RhEja63+uthhBSp5zV1jw9sQXnRDxasPmhuu1QV/i3tq0tQ6QotmZFoFcVIuvC88/ijKoTdk349Ion12XMuf2swRbGrHuEyVfHlSrpLQWcSTylqVJwf8PO+gUmydQ5WDuqfYMV0MSIq+QOlm6TzQzESJ5WN7E7d9FcysLtoFocAU9QImSI7oy4WDo/smOkkekFPATSKhdCaiWPbNMrqNIEmPnYrIy18s2QCp5P0zzIj4FQawTkVuH3DxrJDbHRf1lVa4lqYecXTTrmLJV8KR8o6MlU5thzIlWBY4FzP4LbYBv9q1mjO3He95DlNL6XGsT2lPQKsoN1G/Cv26R8fpYVK4tFDUEWkz3TD8DhEp5mkU5IyO+8KrbSVkzyAU9nqNSk+6wu54c0cYHnNcITMPS5YuD6XRxE0eEZdQquaXel/qHZbtk5nlBsedNAqRTjIZU7nagLKJEewBbuE8t1tfgfGZPqbLYPdO0klD5nnJ+9oImrAvVQVjL/McH/Nz3MobTIdHzgx29LCexLoA7PfbSXNMysgnjQYT3BVPvJnomY/QBtnZ33aXTONve0fjZhTY0O/zOY4cIkfvGOEhQdWth2IWfxq1KxHOXvHU7b1qCg3+7Ow10pIQg1XNHyuhY3sSPGXWcTyg=
  file_glob: true
  file: "${RELEASE_FILES}"
  on:
    branch: master
    tags: true
    condition: "$RELEASE_FILES" != ""
env:
  global:
    secure: J52dK8uM1haWOP5Ktz01VETiYdpyOKtnGZXcZjxEXI7RV+44/MpkSSpKFrIex1jHDodn01Tv+/otmxotaz1HOPv4DgT2gg8FbHlpvnc6+B1/dEaeCDvnd33odmARoOszP0MNFTZdlvg6zGeJwPDYFfITn1jiFBtjazu19VIbQE4D1CSKkWsMXeyH1WjTb0LEtxhYwUcFgNqDb6trArx8xlvZNrh2/j5nPgAzvmuT0JuzwcRz9swwZftKcMjaK5JooSBTydtAzgVpVMZf1q+pF0nR9VlYIY34qQLsWirBjWHGRKdkgAEEN4vEMD1BKbhkIn7TjEpWLrH3BZuJY8uXAfnxvT8KXns2fhA1EDjlP/5n2y1jXAjqCZX8o1dC2fn6qxpL1Qg1WE0n9mhOZLMpbzCpJjBumjQPPUsviggRUs4awSYv3JrYuavvXQZ9rFM634O7CLIDVmbqssVyIYMhgIqLFAWgDxTyAxt+67vUy5ONsAenMOJ6bO36pYZHWH53isCRblUD5nq6Dj6WrW9P7lQhAdhvZ+Hyt+zyVCCblDY9lAv1KetU4i9sDSNYUkQtFTPVBw8LE4JmEctuM7iC6YqeneffPzzDLsGZ70m66VT1L4MYg5h2fGbtRuQ1nPz0+k2CNibN7NegaY35d7gUosnJJF04AeOUcea4+rgQkVM=
