sudo: false
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sed -i -e 's|AC_PREREQ(\[2.69\])|AC_PREREQ([2.68])|' configure.ac
  - pip install --user cpp-coveralls
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - llvm-toolchain-precise
    packages:
    - gcc-4.8
    - g++-4.8
    - clang-3.7
    - libprotobuf-c++
    - protobuf-compiler
    - libprotobuf-dev
script:
  - ./autogen.sh
  - ./configure && make && make check
  - if [ "$CXX" = "g++-4.8" ]; then ./configure --enable-gcov && make && make check; fi
after_success:
  - if [ "$CXX" = "g++-4.8" ]; then coveralls --root './src' --exclude-pattern '.*(include|usr|test|third_party|pb).*' --gcov-options '\-lp'; fi
