sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++" CC="clang"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - autoconf
    - automake
    - libtool
    - libprotobuf-c++
    - protobuf-compiler
    - libprotobuf-dev
script:
  - ./autogen.sh
  - ./configure && make && make check
