sudo: false
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sed -i -e 's|AC_PREREQ(\[2.69\])|AC_PREREQ([2.68])|' configure.ac
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.4" CC="clang-3.4"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - libprotobuf-c++
    - protobuf-compiler
    - libprotobuf-dev
    - gnulib
script:
  - ./autogen.sh
  - ./configure && make && make check
